package azure

// Properties of the Container Group
type ContainerGroupIPAddress struct {
	AutoGeneratedDomainNameLabelScope string          `json:"autoGeneratedDomainNameLabelScope,omitempty"`
	DNSNameLabel                      string          `json:"dnsNameLabel,omitempty"`
	FQDN                              string          `json:"fqdn,omitempty"`
	IP                                string          `json:"ip,omitempty"`
	Ports                             []ContainerPort `json:"ports,omitempty"`
	Type                              string          `json:"type,omitempty"`
}
